### ISSUE TITLE
Pulsefire Dart openRGB support broke

### ISSUE THREAD

**Issue by devils-shadow** [santeri3700/hyperx_pulsefire_dart_reverse_engineering#1]
Hey there, apologies for writing this here but I've been trying to troubleshoot the reason why openRGB refuses to modify any Dart RGB settings despite it being properly detected.

I've tried troubleshooting this on various computers and laptops but the effect is the same everywhere and with every openRGB version I've tried.

Considering you're the person that wrote support for the device to begin with, I thought you'd be able to help me get to the bottom of this mystery. Let me know if you need me to gather any logs or wireshark captures, or anything else and I'll do my best to help. Thank you in advance!

Edit: a link to the original support request thread on GitLab where I also tried raising the issue 
https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/1069

Edit 2; forgot to mention that I'm running Windows10 64bit. Person in the above thread that mentioned their mouse worked with openRGB after the commit appears to be on Linux.

**Comment by santeri3700** [comment]
Hi, thanks for notifying me. I've replied to the Gitlab issue you linked. Let's continue the conversation there.
